### ISSUE TITLE
ValueError: X has 20 features, but SVC is expecting 533454 features as input

### ISSUE THREAD

**Issue by akashrai2003** [keith-golden/gpt2-fake-news#2]
Thanks a lot, I really appreciate your response, actually, I tried this method for Logistic regression at first and after your comment I experimented on SVM too but I ended up getting the same error i.e ValueError: X has 20 features, but SVC is expecting 533454 features as input. Like only fitting on Tfidfvectorizer wasn't enough here as we also did use other functions like TfidfModel( ), doc2bow, Dictionary etc so I tried using the exact methods by hit and trial but ended up getting this same issue where X was able to get only 22 features and required were too much

**Comment by keith-golden** [comment]
Closing this one since I replied on your original ticket
